import type { ReactElement } from 'react';
import Head from 'next/head';
import { Layout } from 'antd';
// import { useRouter } from 'next/router';

import Header from '@/components/header';
import Footer from '@/components/footer';
// import { useAppSelector } from '@/store/hooks';

// const Header = dynamic(() => import('@/components/header'), { ssr: false });

const { Content } = Layout;

const BasicLayout = ({ children }: { children: ReactElement }) => {
  // const router = useRouter();

  // const { isInit } = useAppSelector((store) => store.common);

  // if (router.pathname !== '/' && !isInit) {
  //   return null;
  // }

  return (
    <>
      <Head>
        <title>Smart DAO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Layout>
        <Header type="fix" />
        <Content className="basic">{children}</Content>
        <Footer />
      </Layout>
    </>
  );
};

export default BasicLayout;
